arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.l10n_codegen.dart
synthetic-package: false
nullable-getter: false
header: "// coverage:ignore-file"
untranslated-messages-file: untranslated.txt
