name: carbon_flutter
description: Carbon Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Utility dependencies
  async: ^2.10.0
  clock: ^1.1.1
  collection: ^1.17.0
  convert: ^3.1.1
  fake_async: ^1.3.1
  intl: ^0.19.0
  logging: ^1.1.1

  # Project architecture
  flutter_riverpod: ^2.3.4
  freezed_annotation: ^2.2.0
  go_router: ^14.8.0
  flutter_svg: ^2.0.4
  http: ^1.3.0

  # Device info
  device_info_plus: ^11.3.0
  package_info_plus: ^8.2.1
  connectivity_plus: ^6.1.3
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.0

  # Code generation
  build_runner:
  json_serializable:
  freezed: ^2.3.2

# Flutter toolchain configuration
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
