name: carbon_flutter
description: Carbon Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Utility dependencies
  async: ^2.9.0
  collection: ^1.16.0
  logger: ^1.1.0

  # Project architecture
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  go_router: ^6.0.1
  flutter_svg: ^1.1.6
  http: ^0.13.5
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^2.0.0

  # Code generation
  build_runner:
  flutter_gen:
  flutter_gen_runner:
  json_serializable:
  freezed: ^2.3.2

# Flutter toolchain configuration
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true
